import { getPayload } from 'payload'
import config from '@payload-config'

export const AllSubCategories = [
  {
    id: 2,
    title: 'Подаръци за половинката',
    slug: 'partner',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 3,
    title: 'Подаръци за 8 март',
    slug: '8march',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 4,
    title: 'Подаръци за учители',
    slug: 'teachers',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 5,
    title: 'Подаръци за дипломиране',
    slug: 'graduation',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 6,
    title: 'Подаръци за кръщене',
    slug: 'christening',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 7,
    title: 'Подаръци за баби',
    slug: 'grannies',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 8,
    title: 'Подаръци за бащи',
    slug: 'fathers',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 9,
    title: 'Подаръци за бебета',
    slug: 'babies',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 10,
    title: 'Подаръци за адвокати',
    slug: 'lawyers',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 11,
    title: 'Подаръци за деца',
    slug: 'kids',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 12,
    title: 'Подаръци за гримьорки',
    slug: 'makeup',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 13,
    title: 'Подаръци за дядо',
    slug: 'grandpa',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 14,
    title: 'Подаръци за именден',
    slug: 'namesday',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 15,
    title: 'Подаръци за козметички',
    slug: 'beauty',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 16,
    title: 'Подаръци за зъболекари',
    slug: 'dentists',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 17,
    title: 'Подаръци за лекари',
    slug: 'doctors',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 18,
    title: 'Подаръци за фризьори',
    slug: 'hair',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 19,
    title: 'Кошници с цветя и букети',
    slug: 'flower-baskets',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 4,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 20,
    title: 'Подаръчни кошници',
    slug: 'gift-baskets',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 4,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 21,
    title: 'Уникални 3D лампи',
    slug: 'lamps',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 4,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 22,
    title: 'Гипсови отливки',
    slug: 'gypsum',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 4,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 23,
    title: 'Лазерно гравиране върху метал',
    slug: 'laser-metal',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 4,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 24,
    title: 'Изкушения от дърво',
    slug: 'wood',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 4,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 25,
    title: 'Пакет „Подари песен“',
    slug: 'song',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 2,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 26,
    title: 'Пакет „Изненада на работното място“',
    slug: 'work',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 2,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 27,
    title: 'Пакет „Изненада у дома“',
    slug: 'home',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 2,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 28,
    title: 'Пакет „Изненада по време на разходка“',
    slug: 'walk',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 2,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 29,
    title: 'Пакет „Пътуваща изненада“',
    slug: 'travel',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 2,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 30,
    title: 'Пакет „Романтична вечеря“',
    slug: 'dinner',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 2,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 31,
    title: 'Пакет „Пикник любов“',
    slug: 'picnic',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 2,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 32,
    title: 'Пакет „Годишнина – Нашата история“',
    slug: 'anniversary',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 2,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 33,
    title: 'Пакет „Опознай природата“',
    slug: 'nature',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 2,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 34,
    title: 'Пакет „Бебешка изненада“',
    slug: 'baby',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 2,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 35,
    title: 'SPA пакет в хотел по избор',
    slug: 'spa',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 2,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 36,
    title: 'ATV приключение',
    slug: 'atv',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 5,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 37,
    title: 'Украса и организиране на детски партита и рождени дни',
    slug: 'kids',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 38,
    title: 'Украса и цялостно организиране на рожден ден',
    slug: 'birthday',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 39,
    title: 'Цялостно организиране на сватби и кръщенета',
    slug: 'weddings',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 40,
    title: 'Цялостно организиране на кръщенета',
    slug: 'only-christenings',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 41,
    title: 'Цялостно организиране на балове',
    slug: 'balls',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 42,
    title: 'Цялостно организиране на фирмени мероприятия',
    slug: 'corporate',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 43,
    title: 'Цялостно организиране на училищни празненства',
    slug: 'school',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 44,
    title: 'Кетъринг услуги',
    slug: 'catering',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 45,
    title: 'Арт галерия Меразчиеви',
    slug: 'merazchiev-art-gallery',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 4,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 46,
    title: 'Подаръци за мама',
    slug: 'mother',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 47,
    title: 'Подаръци за маникюристки',
    slug: 'manikur',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 48,
    title: 'Подаръци за рожден ден',
    slug: 'rojden-den',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 49,
    title: 'Подаръци за рибари',
    slug: 'ribari',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 50,
    title: 'Подаръци за ловджии',
    slug: 'lovdjii',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 51,
    title: 'Подаръци за сватба',
    slug: 'svatba',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 52,
    title: 'Подаръци за юбилей',
    slug: 'ubilei',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 53,
    title: 'Подаръци за мъже',
    slug: 'muje',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 54,
    title: 'Подаръци за счетоводители',
    slug: 'schetovoditeli',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 55,
    title: 'Подаръци за шефове',
    slug: 'shev',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 3,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 56,
    title: 'Изненада на работното място',
    slug: 'rabotno-mqsto',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 57,
    title: 'Рафтинг',
    slug: 'rafting',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 5,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 58,
    title: 'Каньонинг',
    slug: 'kanqning',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 5,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 59,
    title: 'Въжена градина и тролей',
    slug: 'vajena-gradina-i-trolei',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 5,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 60,
    title: 'Изненада у дома',
    slug: 'doma',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 61,
    title: 'Изненада по време на разходка',
    slug: 'razhodka',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 62,
    title: 'Пътуваща изненада',
    slug: 'patuvashta-iznenada',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 63,
    title: 'Романтична вечеря',
    slug: 'romantichna-vecherq',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 64,
    title: 'Пикник любов',
    slug: 'piknik',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 65,
    title: 'Годишнина - нашата история',
    slug: 'godishnina',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 66,
    title: 'Опознай природата',
    slug: 'Opoznai-prirodata',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 67,
    title: 'Бебешка изненада',
    slug: 'Bebeshka-iznenada',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 68,
    title: 'Предложение за брак',
    slug: 'Predlojenie-za-brak',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 69,
    title: 'Custom изненада',
    slug: 'custom-iznenada',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 70,
    title: 'SPA пакет в хотел по избор',
    slug: 'spa',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 6,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 71,
    title: 'Чаши',
    slug: 'mugs',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 72,
    title: 'Подаръчни комплекти',
    slug: 'gifts',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 73,
    title: 'Бележници и тефтери',
    slug: 'belejnici-tefteri',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 74,
    title: 'Аксесоари за вино',
    slug: 'aksesoari-za-vino',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 75,
    title: 'Фотоалбуми и фоторамки',
    slug: 'fotoalbimi-fotoramki',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 76,
    title: 'Акрилни сърца и огледала',
    slug: '-',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 77,
    title: 'Манерки',
    slug: 'manerki',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 78,
    title: 'Декорации',
    slug: 'dekoracii',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 79,
    title: 'Лампи',
    slug: 'lampi',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 80,
    title: 'Вази',
    slug: 'vazi',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 81,
    title: 'Часовници',
    slug: 'chasovnici',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 82,
    title: 'Плюшени играчки',
    slug: 'plyusheni-igrachki',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 83,
    title: 'Арома дифузери',
    slug: 'aroma-difuzeri',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 84,
    title: 'Бижутерки',
    slug: 'bizhuterki',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 85,
    title: 'Свещници',
    slug: 'sveshtnici',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 86,
    title: 'Стъклени пожелания',
    slug: 'stakleni-pozhelaniya',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
  {
    id: 87,
    title: 'Цветя',
    slug: 'cvetya',
    meta: {
      title: 'Test',
      image: 2,
      description: '{Title} Под Категория - изберете вашия желан продукт',
    },
    parentCategory: 1,
    slugLock: false,
    _status: 'published',
    updatedAt: '2025-10-30T08:45:56.512Z',
    createdAt: '2025-10-30T08:44:16.900Z',
  },
]

function applyTemplate(
  text: string | undefined,
  item: (typeof AllSubCategories)[0],
): string | undefined {
  if (!text) return text
  return text.replaceAll('{Title}', item.title)
}

async function upsertSubcategory(
  payload: Awaited<ReturnType<typeof getPayload>>,
  item: (typeof AllSubCategories)[number],
) {
  // Prepare final data matching your Payload collection fields (relation fields must be IDs)
  const dataToSave: Record<string, unknown> = {
    title: item.title,
    slug: item.slug,
    slugLock: item.slugLock ?? false,
    _status: item._status ?? 'published',
    parentCategory: item.parentCategory, // relation field expects an ID
    meta: {
      title: item.meta?.title ?? item.title,
      image: item.meta?.image, // relation (single) to media collection
      description: applyTemplate(item.meta?.description, item),
    },
  }

  await payload.create({
    collection: 'sub-category',
    data: dataToSave as any,
  })
  return { action: 'created', slug: item.slug }
}

async function main() {
  const payload = await getPayload({ config })

  // Load your array
  const items: typeof AllSubCategories = AllSubCategories.slice(2)

  // Process sequentially (keeps it simple and respects rate-limits/hooks)
  const results = []
  for (const item of items) {
    // Basic guard
    if (!item.title || !item.slug) {
      results.push({ action: 'skipped', reason: 'missing title/slug', item })
      continue
    }
    results.push(await upsertSubcategory(payload, item))
  }

  // Pretty log
  const created = results.filter((r) => r.action === 'created').length
  const updated = results.filter((r) => r.action === 'updated').length
  const skipped = results.filter((r) => r.action === 'skipped').length
  console.log(`Seed complete. created=${created}, updated=${updated}, skipped=${skipped}`)
}

await main()
